import re

dna = ('ACATTTGCTTCTGACACAACTGTGTTCACTAGCAACCTCAAACAGACACCATGGTGCATCTGACTCCTGA'
       'GGAGAAGTCTGCCGTTACTGCCCTGTGGGGCAAGGTGAACGTGGATGAAGTTGGTGGTGAGGCCCTGGGC'
       'AGGCTGCTGGTGGTCTACCCTTGGACCCAGAGGTTCTTTGAGTCCTTTGGGGATCTGTCCACTCCTGATG'
       'CTGTTATGGGCAACCCTAAGGTGAAGGCTCATGGCAAGAAAGTGCTCGGTGCCTTTAGTGATGGCCTGGC'
       'TCACCTGGACAACCTCAAGGGCACCTTTGCCACACTGAGTGAGCTGCACTGTGACAAGCTGCACGTGGAT'
       'CCTGAGAACTTCAGGCTCCTGGGCAACGTGCTGGTCTGTGTGCTGGCCCATCACTTTGGCAAAGAATTCA'
       'CCCCACCAGTGCAGGCTGCCTATCAGAAAGTGGTGGCTGGTGTGGCTAATGCCCTGGCCCACAAGTATCA'
       'CTAAGCTCGCTTTCTTGCTGTCCAATTTCTATTAAAGGTTCCTTTGTTCCCTAAGTCCAACTACTAAACT'
       'GGGGGATATTATGAAGGGCCTTGAGCATCTGGATTCTGCCTAATAAAAAACATTTATTTTCATTGC')

print "dna is " + dna

start = 0
n = dna.find("ATG",start)
while( n >= 0 ):
    print n
    start = n+1
    n = dna.find("ATG",start)

print "looking for TAG"
start =0
n = dna.find("TAG",start)
while( n >= 0 ):
    print n
    start = n+1
    n = dna.find("TAG",start)

print "looking for TGA"
start =0
n = dna.find("TGA",start)
while( n >= 0 ):
    print n
    start = n+1
    n = dna.find("TGA",start)

print "looking for TAA"
start = 0
n = dna.find("TAA",start)
while( n >= 0 ):
    print n
    start = n+1
    n = dna.find("TAA",start)

